services:
  # Main comment database (only service with volume)
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: comment_user
      POSTGRES_PASSWORD: comment_password
      POSTGRES_DB: comments_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U comment_user -d comments_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  importer:
    build:
      context: .
      dockerfile: ./importer/Dockerfile
    environment:
      DATABASE_URL: "postgresql://comment_user:comment_password@db:5432/comments_db"
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  sentiment_api:
    build:
      context: .
      dockerfile: ./model/Dockerfile
    ports:
      - "5001:5000"
    environment:
      - MODEL_NAME=SZTAKI-HLT/hubert-base-cc
      - MAX_LENGTH=128
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5000/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      importer:
        condition: service_completed_successfully

  sentiment_processor:
    build:
      context: .
      dockerfile: ./sentiment_processor/Dockerfile
    environment:
      DATABASE_URL: "postgresql://comment_user:comment_password@db:5432/comments_db"
      SENTIMENT_API_URL: "http://sentiment_api:5000/predict"
    depends_on:
      sentiment_api:
        condition: service_healthy
    restart: unless-stopped

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://comment_user:comment_password@db:5432/comments_db"
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      sentiment_processor:
        condition: service_started

volumes:
  postgres_data:

