version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: sentiment_user
      POSTGRES_PASSWORD: sentiment_pass
      POSTGRES_DB: sentiment_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentiment_user -d sentiment_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  sentiment-api:
    build:
      context: .
      dockerfile: model/Dockerfile
    ports:
      - "5001:5000"
    environment:
      - MODEL_NAME=SZTAKI-HLT/hubert-base-cc
      - MAX_LENGTH=128
      - DATABASE_URL=postgresql://sentiment_user:sentiment_pass@db:5432/sentiment_db
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  web-client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      sentiment-api:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - API_URL=http://sentiment-api:5000/predict
      - DATABASE_URL=postgresql://sentiment_user:sentiment_pass@db:5432/sentiment_db
      - SECRET_KEY=your-secret-key-here
    restart: unless-stopped

volumes:
  postgres_data:

