version: '3.8'

services:
  sentiment-api:
    build: ./model
    ports:
      - "5001:5000"
    volumes:
      - ./model:/app
    environment:
      - MODEL_NAME=SZTAKI-HLT/hubert-base-cc
      - MAX_LENGTH=128
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3

  web-client:
    build: ./client
    ports:
      - "5000:5000"
    depends_on:
      sentiment-api:
        condition: service_healthy
    environment:
      - API_URL=http://sentiment-api:5000/predict
    restart: on-failure

